### ISSUE TITLE
Getting this issue : Error: Cannot find module 'preq'

### ISSUE THREAD

**Issue by Gauravsanganan** [wikimedia/html-metadata#87]
Error: Cannot find module 'preq'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sinhagaurav010/Documents/CICD/ved_backend/node_modules/html-metadata/index.js:15:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sinhagaurav010/Documents/CICD/ved_backend/routes/PostRoute2.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

Please fix

**Comment by mvolz** [comment]
Have you done 

> npm i

To install the dependencies?

**Comment by aptvaibhav** [comment]
u need to write npm init command.
